export const ALL_BOOK_SUCCESS = "ALL_BOOK_SUCCESS";
export const ALL_BOOK_FAIL = "ALL_BOOK_FAIL";

export const SINGLE_BOOK_SUCCESS = "SINGLE_BOOK_SUCCESS";
export const SINGLE_BOOK_FAIL = "SINGLE_BOOK_FAIL";