export const ALL_BOOK_REQUEST = "ALL_BOOK_REQUEST";
export const ALL_BOOK_SUCCESS = "ALL_BOOK_SUCCESS";
export const ALL_BOOK_FAIL = "ALL_BOOK_FAIL";

export const SINGLE_BOOK_REQUEST = "SINGLE_BOOK_REQUEST";
export const SINGLE_BOOK_SUCCESS = "SINGLE_BOOK_SUCCESS";
export const SINGLE_BOOK_FAIL = "SINGLE_BOOK_FAIL";

export const NEW_BOOK_REQUEST = "NEW_BOOK_REQUEST";
export const NEW_BOOK_SUCCESS = "NEW_BOOK_SUCCESS";
export const NEW_BOOK_RESET = "NEW_BOOK_RESET";
export const NEW_BOOK_FAIL = "NEW_BOOK_FAIL";