export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SINGLE_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const SINGLE_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const PROFILE_UPDATE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const PROFILE_UPDATE_RESET = "UPDATE_PROFILE_RESET";
export const PROFILE_UPDATE_FAIL = "UPDATE_PROFILE_FAIL";